# Generated by Django 2.2.1 on 2019-06-01 04:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 1, 4, 55, 38, 787299)),
        ),
    ]
